name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  prettier:
    name: 'Check Prettier Styles'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'yarn'

      - name: Installing dependencies
        run: yarn install --frozen-lockfile

      - name: Run Prettier checks
        run: yarn prettier:check

  eslint:
    name: 'Check ESLint Rules'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'yarn'

      - name: Installing dependencies
        run: yarn install --frozen-lockfile

      - name: Run ESLint checks
        run: yarn lint:check

  test-eslint-plugin-axios:
    name: 'Run tests for @adalo/eslint-plugin-axios'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'yarn'

      - name: Installing dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test:eslint-plugin-axios

  test-build:
    name: 'Test builds'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'yarn'

      - name: Installing dependencies
        run: yarn install --frozen-lockfile

      - name: Run build
        run: yarn build

  release-version:
    name: 'Release new version to NPM'
    needs: ['prettier', 'eslint', 'test-eslint-plugin-axios', 'test-build']
    if: "github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, 'skip release')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          # Token with higher permissions is required for lerna to push versions
          token: ${{ secrets.GITHUB_TOKEN }}

      # Sets the github action user as the author of the version commits
      - uses: fregante/setup-git-user@v1

      # Fetch all history for all tags and branches in this job because lerna needs it
      - run: |
          git fetch --prune --unshallow

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'
          scope: '@adalo'
          cache: 'yarn'
          # actions/setup-node writes a .npmrc file which includes _authToken=${NODE_AUTH_TOKEN}
          # This allows setting NODE_AUTH_TOKEN when running any npm or yarn command
          # See: https://github.com/actions/setup-node/blob/v3.1.1/src/authutil.ts#L47-L48

      - name: Installing dependencies
        run: yarn install --frozen-lockfile

      - name: Build packages
        run: yarn build

      # Increments package versions based on commits since the last release and publishes the new version to github.
      # Version increments follow the Conventional Commits specification.
      # See: https://www.conventionalcommits.org/en/v1.0.0/
      - name: Release new version and publish to NPM
        # --no-verify-access is needed because lerna does not correctly handle NPM automation tokens for the verification step.
        # See: https://github.com/lerna/lerna/issues/2788#issuecomment-776726711
        run: npx lerna publish --conventional-commits --exact --no-verify-access --yes
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
