name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  prettier:
    name: 'Check Prettier Styles'

    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'yarn'

      - name: Installing dependencies
        run: yarn install --frozen-lockfile

      - name: Run Prettier checks
        run: yarn prettier:check

  eslint:
    name: 'Check ESLint Rules'

    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'yarn'

      - name: Installing dependencies
        run: yarn install --frozen-lockfile

      - name: Run ESLint checks
        run: yarn lint:check

  test-eslint-plugin-axios:
    name: 'Run tests for @adalo/eslint-plugin-axios'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'yarn'

      - name: Installing dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test:eslint-plugin-axios

  update-versions:
    name: 'Publish to NPM'

    needs: ['prettier', 'eslint', 'test-eslint-plugin-axios']

    if: "github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, 'skip publish')"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          # Token with higher permissions is required for lerna to push versions
          token: ${{ secrets.GITHUB_TOKEN }}

      # Sets the github action user as the author of the version commits
      - uses: fregante/setup-git-user@v1

      # Fetch all history for all tags and branches in this job because lerna needs it
      - run: |
          git fetch --prune --unshallow

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'yarn'

      - name: Installing dependencies
        run: yarn install --frozen-lockfile

      # Creates the new version and pushes to github
      - name: Update Versions
        run: npx lerna version --conventional-commits --exact --yes

      - name: Publish to NPM
        run: npx lerna publish --yes
        env:
          NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
