name: Static Analysis

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  prettier:
    name: 'Check Prettier Styles'

    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Installing dependencies
        run: yarn install --frozen-lockfile

      - name: Run Prettier checks
        run: yarn prettier:check

  eslint:
    name: 'Check ESLint Rules'

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Installing dependencies
        run: yarn install --frozen-lockfile

      - name: Run ESLint checks
        run: yarn lint:check
