name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  eslint-plugin-axios:
    name: '@adalo/eslint-plugin-axios'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Installing dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test:eslint-plugin-axios
